#!/bin/bash

function check_failure() {
    exit_code=$1

    if [ $1 -ne 0 ]; then
        echo "Process failed."
        exit 1
    fi
}

# https://docs.docker.com/engine/install/ubuntu
echo "Uninstall old versions"
echo "[CMD] Try to remove docker engine."
sudo apt-get remove docker docker-engine docker.io containerd runc

# https://docs.docker.com/engine/install/ubuntu
echo "Install using the repository"
echo "Set up the repository"
echo "Update the apt package index and install packages to allow apt to use a repository over HTTPS"

sudo apt-get update
check_failure $?

sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release -y
check_failure $?

echo "Add Docker’s official GPG key"
sudo mkdir -p /etc/apt/keyrings
check_failure $?

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
check_failure $?

echo "Use the following command to set up the repository"
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list

echo "Install Docker Engine"
sudo apt-get update
check_failure $?

sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
check_failure $?

echo "Grant read and write permission to all users"
sudo chmod 666 /var/run/docker.sock
